#!/bin/bash
# Begin LSF Directives
#BSUB -J high_f_large_1layer
#BSUB -P geo112
#BSUB -W 07:00
#BSUB -nnodes 312
#BSUB -alloc_flags "gpumps smt1"
##BSUB -alloc_flags maximizegpfs
#BSUB -o run_%J.out
#BSUB -e run_%J.err
##BSUB -N

export OMP_NUM_THREADS=1
cd $LS_SUBCWD

module unload darshan-runtime
module load cuda

cat $0
args=$(cat param.sh)
echo $args

jsrun -n 1872 -a 3 -c 3 -g 1 -r 6 -d cyclic /ccs/home/hzfmer/awp_highf/pmcl3d_qs150_vs500 $args
