#!/bin/bash -l
# BEGIN LSF Directives
#BSUB -J GVDA_1d_150m
#BSUB -P geo112
#BSUB -W 00:16
#BSUB -nnodes 4
#BSUB -alloc_flags "gpumps smt1"
#BSUB -o run_%J.out
#BSUB -e run_%J.err
##BSUB -N

cd $LS_SUBCWD
module unload darshan-runtime
module load cuda

args=`cat param.sh`
echo "Starting run.lfs.$(date)"
cat $0
echo $args
jsrun -n 16 -a 3 -c 3 -g 1 -r 4 -d cyclic /ccs/home/hzfmer/code_gpu_preevents_dm/pmcl3d $args
echo "Ending.$(date)"
