#!/bin/bash -l
#PBS -A geo112
#PBS -l nodes=16
#PBS -l walltime=00:15:00
#PBS -N pt_src_GVDA
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
##PBS -M zhh076@ucsd.edu

cd $PBS_O_WORKDIR

export MPICH_RANK_REORDER_DISPLAY=1
export MPICH_RANK_REORDER_METHOD=0
export PMI_NO_FORK=1

module swap PrgEnv-pgi PrgEnv-gnu
module load cudatoolkit

args=`cat param.sh`
echo "Starting run.pbs.$(date)"
echo $args
aprun -n 48 -N 3 /ccs/home/hzfmer/code_gpu_preevents_dm/pmcl3d $args
echo "Ending.$(date)"
