#!/bin/bash -l
# BEGIN LSF Directives
#BSUB -J TTF_1D_TKCH05
#BSUB -P geo112
#BSUB -W 00:15
#BSUB -nnodes 4
#BSUB -alloc_flags "gpumps smt1"
#BSUB -o %J.out
#BSUB -e %J.err
##BSUB -N

cd $LS_SUBCWD
module unload darshan-runtime
module load cuda

args=`cat param_borehole.sh`
echo "Starting run_borehole.lfs.$(date)"
cat $0
echo $args
jsrun -n 16 -a 3 -c 3 -g 1 -r 4 -d cyclic /ccs/home/hzfmer/scratch/AWP-ODC-YFSWP/pmcl3d $args
echo "Ending.$(date)"
