#!/bin/bash -l
#PBS -A GEO112
#PBS -l nodes=391
#PBS -l walltime=00:10:00
#PBS -N extract_cvm
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
##PBS -M zhh076@ucsd.edu

module load iobuf
module swap PrgEnv-pgi PrgEnv-gnu

echo "STARTING `date`"
cd $PBS_O_WORKDIR
DIR=/lustre/atlas/proj-shared/geo112/huzf/ucvm-17.1.0
UCVMBIN=$DIR/bin
aprun -n 6250 $UCVMBIN/ucvm2mesh-mpi -f ucvm_la_habra_small.conf 
echo "ENDING `date`"
